feat: start readme in convnet and create train notebook with open dataset
MetisPoly/Classification pull request #6
Opened 2022-09-23 01:13 UTC by lucaslepore

2022-09-23 17:07 UTC, MetisPolyMtl commented on Modele_prediction/Modele_regression/ConvNet/README.md
> +We propose a convnet deeplearning network using electromencephatographic(EEG) data as input to predict the angle of different motors. These motors will be the main driving unit for an exosquelletton
Could change EEG for EMG?

exosquelleton -> exoskeleton

to help people attain with dysmorphie musculaire -> to help people suffering from muscular dystrophy ;)

2022-09-23 17:09 UTC, tadamo3 commented on Modele_prediction/Modele_regression/ConvNet/README.md
> +We propose a convnet deeplearning network using electromencephatographic(EEG) data as input to predict the angle of different motors. These motors will be the main driving unit for an exosquelletton
Could change EEG for EMG?

exosquelleton -> exoskeleton

to help people attain with dysmorphie musculaire -> to help people suffering from muscular dystrophy ;)

2022-09-23 19:21 UTC, tadamo3 requested changes

2022-09-23 19:21 UTC, tadamo3 commented on Modele_prediction/Modele_regression/ConvNet/README.md
> +We propose a convnet deeplearning network using electromencephatographic(EEG) data as input to predict the angle of different motors. These motors will be the main driving unit for an exosquelletton
Could change EEG to EMG

exosquelletton -> exoskeleton

'to help people attain with dysmorphie musculaire' -> 'to help people suffering from muscular dystrophy'

2022-09-27 23:14 UTC, MetisPolyMtl approved these changes

2022-09-27 23:15 UTC, tadamo3 approved these changes

2022-09-29 21:19 UTC, merged